name:                encoding-lab01
version:             0.1.0.0
github:              "vasalf/encoding-lab01"
license:             BSD3
author:              "Vasily Alferov"
maintainer:          "vasily.v.alferov@gmail.com"
copyright:           "2020 Vasily Alferov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vasalf/encoding-lab01#readme>

dependencies:
- base >= 4.7 && < 5
- matrix
- vector
- MonadRandom
- poly
- semirings

library:
  source-dirs: src

executables:
  encoding-lab01-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - encoding-lab01
